-- Store validated contact-form submissions with length limits enforced again at
-- the database boundary. requester_hash supports private rate limiting.
create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  name text not null check (char_length(name) between 1 and 100),
  email text check (email is null or char_length(email) <= 254),
  subject text not null check (char_length(subject) between 1 and 120),
  message text not null check (char_length(message) between 10 and 4000),
  requester_hash text not null,
  status text not null default 'new' check (status in ('new', 'read', 'resolved', 'spam')),
  created_at timestamptz not null default now()
);

-- Speed up recent-message lookups for a single anonymous requester.
create index if not exists contact_messages_requester_created_idx
  on public.contact_messages (requester_hash, created_at desc);

-- Browser roles receive no direct access; trusted server code mediates requests.
alter table public.contact_messages enable row level security;

-- Contact messages are available only to trusted server-side service-role code.
-- Public visitors may submit through the validated Edge Function but cannot
-- query, update, or delete the table directly.
revoke all on table public.contact_messages from anon, authenticated;
revoke all on sequence public.contact_messages_id_seq from anon, authenticated;
